name: Build Marlin Firmware

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Build Firmware
      run: |
        cd Marlin
        pio run -e jgaurora_a5s_skr_mini_e3_v2
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: marlin-firmware
        path: |
          Marlin/.pio/build/jgaurora_a5s_skr_mini_e3_v2/firmware.bin
          Marlin/.pio/build/jgaurora_a5s_skr_mini_e3_v2/firmware.hex
        retention-days: 30
        
    - name: Create Release
      if: github.event_name == 'release'
      run: |
        echo "Release created: ${{ github.event.release.tag_name }}"
        echo "Firmware built successfully!"
